### DISCUSSION TITLE
options to postgres configuration file

### DISCUSSION THREAD

**Discussion by david-whimsical** [tconbeer/harlequin#472] [Ideas (Feature Requests)]
hey!

First of all, thanks for building Harlequin. I've never understood why SQL IDEs felt so old and clunky, and this is an excellent alternative to working in VSCode!

I tried to run Harlequin with this configuration today:

```toml
# .harlequin.toml
default_profile = "david"

[profiles.david]
theme = "dracula"
limit = 500
adapter = "postgres"
host = "hostname"
user = "david"
password = "password"
dbname = "dbname"
port = 5432
options = "-c search_path=etl_david" #here!
```

I hoped Harlequin would run with the command following the `-c` flag.
See https://www.postgresql.org/docs/current/app-psql.html

For context, my use-case is to work in a different schema than the default `public` (ie. `etl_david`)

I've no idea how hard this would be to support, but that'd be a very nice thing to have in my opinion! 😊
