### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin#206]
Theme, extensions...
From current project or user dir?

**Comment by tconbeer** [comment]
https://github.com/petereon/beaupy is based on Rich, which is nice.

**Comment by tconbeer** [comment]
Questionary also looks good and lightweight deps wise.

**Comment by tconbeer** [comment]
```toml
default_profile = "my-duckdb-profile"

[profile.my-duckdb-profile]
theme = "monokai"
init_path = "~/.duckdbrc"
limit = 100_000

[profile.my-duckdb-profile.adapter]
kind = "duckdb"
path = ":memory:"
read_only = false
allow_unsigned_extensions = false
extension = ["httpfs", "spatial"]
force_install_extensions = false
md_saas = false

[profile.local-postgres]
theme = "fruity"
init_path = "~/.psqlrc"
limit = 1_000

[profile.local-postgres.adapter]
kind = "postgres"
host = "localhost"
user = "postgres"
password = "secretadminpassword"
database = "postgres"
port = 5432
```
